#title : mingi's blog
#summary : notes for something.
#site_authors : Mingi Choi
#date : September 14, 2020
copyright : 2020 Mingi Choi all right reserved.
site_name: blog
nav:
    - Home: index.md
    - 1: build-blog-using-mkdocs.md
    - About: about.md
theme: readthedocs
markdown_extensions:
    - toc:
          permalink: "#"
          baselevel: 2
          separator: "_"