# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: prepare env
        run: pip install mkdocs
       
      - name: move
          git clone "https://github.com/Maznna/blog.git"
          echo "clone"
          ls
          cd blog-source
          mkdocs build -d ../blog
          echo "build"
          cd ../blog
          pwd
          git remote add blog "https://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@github.com/Maznna/blog.git"
          git config user.name "mingi-action"
          git config user.email "mingi-action-no-reply@b.com"
          echo "configed"
          git add -A
          echo "git add"
          git commit -m "auto commit by action"
          echo "after commit"
          git push blog --force